adding formal support for Node 6
- use `require("@withjoy/server-core/dist/node6")`
- added npm-shrinkwrap.json

when `typescript` went from 3.8 => 3.9, we started to have issues in `app-server-api`:

```
exports.EntityManager = EntityManager_1.EntityManager;

TypeError: Cannot set property EntityManager of #<Object> which has only a getter
    at Object.<anonymous> (/jRunBad/node_modules/typeorm/index.js:117:23)
```

it seems that `Reflect.getOwnPropertyDescriptor(exports, 'EntityManager')` produces different results:

- TypeScript 3.8 => `{"writable":true,"enumerable":true,"configurable":true}`
- TypeScript 3.9 => `{"enumerable":true,"configurable":false}`

the best approach is to create a Node-6-specific `index.js` and only expose those things that `app-server-api` and the other monorepo modules really need (because they sure don't need `typeorm`).